// UI Components - ElevenLabs Integration
export { Matrix } from './matrix'
export { Orb } from './orb'
export { MicSelector } from './mic-selector'
export { VoicePicker } from './voice-picker'
export { AudioPlayerProvider, AudioPlayerButton, AudioPlayerProgress, AudioPlayerTime, AudioPlayerDuration, AudioPlayerSpeed, AudioPlayerSpeedButtonGroup } from './audio-player'
export { ShimmeringText } from './shimmering-text'

// Existing UI Components
export { Button } from './button'
export { Card } from './card'
export { Badge } from './badge'
export { Dialog } from './dialog'
export { Popover } from './popover'
export { DropdownMenu } from './dropdown-menu'
export { Command } from './command'
export { Input } from './input'
export { Label } from './label'
export { Textarea } from './textarea'
export { Select } from './select'
export { Switch } from './switch'
export { Checkbox } from './checkbox'
export { Tabs } from './tabs'
export { Separator } from './separator'
export { Progress } from './progress'
export { ScrollArea } from './scroll-area'
export { HoverCard } from './hover-card'
export { Collapsible } from './collapsible'
export { Tooltip } from './tooltip'
export { Alert } from './alert'
export { Avatar } from './avatar'
export { Carousel } from './carousel'
